language: minimal

services: docker

before_install:

  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed tmurphy605/udagram-api-feed:v2
  - docker tag udagram-api-user tmurphy605/udagram-api-user:v2
  - docker tag udagram-frontend tmurphy605/udagram-frontend:v2
  - docker tag udagram-reverseproxy tmurphy605/udagram-reverseproxy:v2


  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tmurphy605/udagram-api-feed:v2
  - docker push tmurphy605/udagram-api-user:v2
  - docker push tmurphy605/udagram-frontend:v2
  - docker push tmurphy605/udagram-reverseproxy:v2
